const express = require("express")
const router = express.Router()
const admincontroller = require("../controllers/adminccontroller")
const authMiddlewares = require("../middlewares/authAdminMiddleware")


router.post("/adminlogin",admincontroller.adminLogin)
router.post("/mechanicregistration",admincontroller.mechanicRegistration)
router.get("/mechaniclist",authMiddlewares,admincontroller.displayMechanic)
router.post("/mechanicedit",authMiddlewares,admincontroller.mechanicEdit)
router.post("/mechanicblock",authMiddlewares,admincontroller.mechanicBlock)
router.get("/userdetails",authMiddlewares,admincontroller.userList)
router.get("/adminusercount",authMiddlewares,admincontroller.adminusercount)
router.get("/adminservicecount",authMiddlewares,admincontroller.adminservicecount)
router.get("/adminmechaniccount",authMiddlewares,admincontroller.mechanicCount)
router.get("/mechanicworkscount",authMiddlewares,admincontroller.mechanicWorksCount)
router.get("/totalrevenue",authMiddlewares,admincontroller.totalRevenue)
router.post("/block",authMiddlewares,admincontroller.userBlock)
router.post("/userunblock/:id",admincontroller.userunBlock)
router.get("/servicetable",authMiddlewares,admincontroller.serviceTable)
router.get("/getmechanic",authMiddlewares,admincontroller.mechanicService)
router.post("/updateservicetable/:id",authMiddlewares,admincontroller.updateStatusofservice)    
router.post("/assignmechanic/:id",authMiddlewares,admincontroller.mechAssign)      
router.post("/getdone/:id",authMiddlewares,admincontroller.getDone)    

module.exports = router